ALTER TABLE dbo.TRADE
    ALTER COLUMN TRADE_AMOUNT_SYMBOL1 varchar(50) null
ALTER TABLE dbo.TRADE
    ALTER COLUMN TRADE_AMOUNT_SYMBOL2 varchar(50) null
ALTER TABLE dbo.TRADE
    ALTER COLUMN TRADE_PAIR_LIMIT varchar(50)
ALTER TABLE dbo.TRADE
    ALTER COLUMN TRADE_AMOUNT_LIMIT varchar(50)
ALTER TABLE dbo.TRADE
    ALTER COLUMN TRADE_SYMBOL varchar(30) null
ALTER TABLE dbo.TRADE
    ALTER COLUMN TRADE_TRANSACTIME bigint null
ALTER TABLE dbo.TRADE
    ALTER COLUMN TRADE_TYPE varchar(50) null
ALTER TABLE dbo.TRADE
    ALTER COLUMN TRADE_SIDE varchar(50) null

ALTER TABLE dbo.STRATEGY
    ALTER COLUMN STRATEGY_SYMBOL1 varchar(50) null
ALTER TABLE dbo.STRATEGY
    ALTER COLUMN STRATEGY_SYMBOL2 varchar(50) null
ALTER TABLE dbo.STRATEGY
    ALTER COLUMN STRATEGY_PRIME varchar(50) null

ALTER TABLE dbo.WALLET
    ALTER COLUMN WALLET_BALANCE_SYMBOL varchar(50) null
ALTER TABLE dbo.WALLET
    ALTER COLUMN WALLET_BALANCE_TOTAL varchar(50) null

ALTER TABLE dbo.WALLET_HISTORY
    ALTER COLUMN WALLET_HISTORY_SYMBOL varchar(50) null
ALTER TABLE dbo.WALLET_HISTORY
    ALTER COLUMN WALLET_HISTORY_TOTAL varchar(50) null
ALTER TABLE dbo.USER_DATA
    ALTER COLUMN USER_PASSWORD varchar(150) not null
