/*==============================================================*/
/*				TEST DATA  for Solidr							*/
/*			Date de création :  23/11/2020 00:00:00             */
/*==============================================================*/


SET DATEFORMAT ymd

INSERT INTO dbo.API_CORP(API_LABEL, API_LINK, API_ICON) VALUES ('Binance', 'www.binance.com.ex', 001)
INSERT INTO dbo.API_CORP(API_LABEL, API_LINK, API_ICON) VALUES ('Liquid', 'www.liquid.com.ex', 002)
INSERT INTO dbo.API_CORP(API_LABEL, API_LINK, API_ICON) VALUES ('Bittrex', 'www.bittrex.com.ex', 003)
INSERT INTO dbo.API_CORP(API_LABEL, API_LINK, API_ICON) VALUES ('KuCoin', 'www.kucoin.com.ex', 004)
INSERT INTO dbo.API_CORP(API_LABEL, API_LINK, API_ICON) VALUES ('Kraken', 'www.kraken.com.ex', 005)
INSERT INTO dbo.API_CORP(API_LABEL, API_LINK, API_ICON) VALUES ('HitBTC', 'www.hitbtc.com.ex', 006)


INSERT INTO dbo.FONCTION(FONCTION_LABEL, FONCTION_DESCRIPTION) VALUES ('CRUDS', 'Create-Read-Update-Update-Subscribe')
INSERT INTO dbo.FONCTION(FONCTION_LABEL, FONCTION_DESCRIPTION) VALUES ('CRUD', 'Create-Read-Update-Update')
INSERT INTO dbo.FONCTION(FONCTION_LABEL, FONCTION_DESCRIPTION) VALUES ('CRU', 'Create-Read-Update')
INSERT INTO dbo.FONCTION(FONCTION_LABEL, FONCTION_DESCRIPTION) VALUES ('R', 'Read')
INSERT INTO dbo.FONCTION(FONCTION_LABEL, FONCTION_DESCRIPTION) VALUES ('S', 'Subscribe')
INSERT INTO dbo.FONCTION(FONCTION_LABEL, FONCTION_DESCRIPTION) VALUES ('URDS', 'Create-Update')
INSERT INTO dbo.FONCTION(FONCTION_LABEL, FONCTION_DESCRIPTION) VALUES ('U', 'Create-Update')



INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION) VALUES ('Symbol', 'BTC', 'Bitcoin')
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION) VALUES ('Symbol', 'LTC', 'Litecoin')
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION) VALUES ('Symbol', 'ETH', 'Ethereum')
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION) VALUES ('Symbol', 'XRP', 'Ripple')
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Symbol', 'USDT', 'Tether')
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Symbol', 'LIBRA', 'Libra')
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Symbol', 'XMR', 'Monero')
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Symbol', 'BNB', 'BinanceCoin')
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Symbol', 'EOS', 'EoSio')
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Symbol', 'NANO', 'Nano')
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Symbol', 'VTC', 'VertCoin')
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Symbol', 'XVG', 'Verge')
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Symbol', 'XLM', 'Stellar')
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Symbol', 'XEM', 'Nem')
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Picture', '01', 'Picture 01');
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Picture', '02', 'Picture 02');
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Picture', '03', 'Picture 03');
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Picture', '04', 'Picture 04');
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Picture', '05', 'Picture 05');
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Picture', '06', 'Picture 06');
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Picture', '07', 'Picture 07');
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Picture', '08', 'Picture 08');
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Picture', '09', 'Picture 09');
INSERT INTO dbo.INFORMATION(INFORMATION_TYPE, INFORMATION_CODE, INFORMATION_DESCRIPTION)
VALUES ('Picture', '10', 'Picture 10');


INSERT INTO dbo.PROFIL(PROFIL_LABEL, PROFIL_DESCRIPTION)
VALUES ('Admin', 'Privilege!!! This person has privilege.')
INSERT INTO dbo.PROFIL(PROFIL_LABEL, PROFIL_DESCRIPTION)
VALUES ('Staff', 'This is an employee.')
INSERT INTO dbo.PROFIL(PROFIL_LABEL, PROFIL_DESCRIPTION)
VALUES ('Member', 'This is a member.')
INSERT INTO dbo.PROFIL(PROFIL_LABEL, PROFIL_DESCRIPTION)
VALUES ('Expert', 'This person can manage their own strategies.')
INSERT INTO dbo.PROFIL(PROFIL_LABEL, PROFIL_DESCRIPTION)
VALUES ('User', 'Basic account, nothing special.')


INSERT INTO dbo.STATUS(STATUS_LABEL, STATUS_DESCRIPTION) VALUES ('New', 'Status type.')
INSERT INTO dbo.STATUS(STATUS_LABEL, STATUS_DESCRIPTION) VALUES ('Connected', 'Status type.')
INSERT INTO dbo.STATUS(STATUS_LABEL, STATUS_DESCRIPTION) VALUES ('Offline', 'Status type.')
INSERT INTO dbo.STATUS(STATUS_LABEL, STATUS_DESCRIPTION) VALUES ('Visitor', 'Status type.')
INSERT INTO dbo.STATUS(STATUS_LABEL, STATUS_DESCRIPTION) VALUES ('Online', 'Status type.')
INSERT INTO dbo.STATUS(STATUS_LABEL, STATUS_DESCRIPTION) VALUES ('Updated', 'Status type.')
INSERT INTO dbo.STATUS(STATUS_LABEL, STATUS_DESCRIPTION) VALUES ('Day', 'Status type.')
INSERT INTO dbo.STATUS(STATUS_LABEL, STATUS_DESCRIPTION) VALUES ('Week', 'Status type.')
INSERT INTO dbo.STATUS(STATUS_LABEL, STATUS_DESCRIPTION) VALUES ('Month', 'Status type.')
INSERT INTO dbo.STATUS(STATUS_LABEL, STATUS_DESCRIPTION) VALUES ('Activated', 'Status type.')
INSERT INTO dbo.STATUS(STATUS_LABEL, STATUS_DESCRIPTION) VALUES ('Desactivated', 'Status type.')



INSERT INTO dbo.USER_DATA(USER_EMAIL, STATUS_ID, USER_PASSWORD, USER_USERNAME, USER_FIRSTNAME, USER_LASTNAME, USER_BIRTHDATE, USER_SIGNIN, USER_DESCRIPTION, USER_LINK_CONTACT, USER_GAZ, USER_TOKEN, USER_USING2FA, USER_ENABLED) VALUES (N'test@test.com', 10, '$2a$10$Unfr1mc.JmRSoddCLv3dXO4WSIDNeMDW1A2foubGvkP.OLeVjhscW', 'test', 'test', 'test', '2000-01-01 00:00:00', '2019-06-09 13:15:58', 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatu','test@account.com', 36.91, 'd11e4dec-dcfc-4fc8-809c-45c70019a32f', 0, 1)
INSERT INTO dbo.USER_DATA(USER_EMAIL, STATUS_ID, USER_PASSWORD, USER_USERNAME, USER_FIRSTNAME, USER_LASTNAME, USER_BIRTHDATE, USER_SIGNIN, USER_DESCRIPTION, USER_LINK_CONTACT, USER_GAZ, USER_TOKEN, USER_USING2FA, USER_ENABLED) VALUES (N'admin@test.com', 10, '$2a$10$LyJPKLJeY8JoEy.E1jxxNuYOKXp7lGTrUxaO9Nu1VmyrrOfdSL6s6', 'admintest', 'Admin', 'Admin', '1985-07-09 00:00:00', '2010-06-09 13:15:58', 'Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.', 'admin@test.com', 236.91, 'a3284c9a-f272-41f1-aba1-4c7c193db4d7', 0, 1)
INSERT INTO dbo.USER_DATA(USER_EMAIL, STATUS_ID, USER_PASSWORD, USER_USERNAME, USER_FIRSTNAME, USER_LASTNAME, USER_BIRTHDATE, USER_SIGNIN, USER_DESCRIPTION, USER_LINK_CONTACT, USER_GAZ, USER_TOKEN, USER_USING2FA, USER_ENABLED) VALUES (N'staff@test.com', 10, '$2a$10$5NY9uf8CfZt6aFmjKzvQk.jOkCaid2WJmnT2nqsz9C/ItJnnhE3/K', 'stafftest', 'Staff', 'Staff', '1988-03-24 00:00:00', '2013-11-19 16:03:46', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', 'staff@test.com', 518.43, '8bed844a-22b7-4096-ac01-f9955f19ee05', 0, 1)
INSERT INTO dbo.USER_DATA(USER_EMAIL, STATUS_ID, USER_PASSWORD, USER_USERNAME, USER_FIRSTNAME, USER_LASTNAME, USER_BIRTHDATE, USER_SIGNIN, USER_DESCRIPTION, USER_LINK_CONTACT, USER_GAZ, USER_TOKEN, USER_USING2FA, USER_ENABLED) VALUES (N'expert@test.com', 10, '$2a$10$GrlbvByyLv2e3Ytzhl2y8u/bkaf0oqSWtjelNeUx8qPHgUiYnNqui', 'experttest', 'Expert', 'Expert', '1960-11-10 00:00:00', '2019-06-26 09:43:29', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium', 'expert@test.com', 151.63, 'd6908757-65b5-4141-8d33-98e23e50a644', 0, 1)
INSERT INTO dbo.USER_DATA(USER_EMAIL, STATUS_ID, USER_PASSWORD, USER_USERNAME, USER_FIRSTNAME, USER_LASTNAME, USER_BIRTHDATE, USER_SIGNIN, USER_DESCRIPTION, USER_LINK_CONTACT, USER_GAZ, USER_TOKEN, USER_USING2FA, USER_ENABLED) VALUES (N'member@test.com', 10, '$2a$10$CN19sv97CfVJB6P8YFX1yuKFQwAE47nDo6KL5NmtI3Hl.QtXDUuZK', 'membertest', 'Member', 'Member', '1973-04-18 00:00:00', '2019-02-14 14:43:47', 'totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'member@test.com', 153.52, '0a3b3662-2a45-46b6-977e-adbf39f060ef', 0, 1)
INSERT INTO dbo.USER_DATA(USER_EMAIL, STATUS_ID, USER_PASSWORD, USER_USERNAME, USER_FIRSTNAME, USER_LASTNAME, USER_BIRTHDATE, USER_SIGNIN, USER_DESCRIPTION, USER_LINK_CONTACT, USER_GAZ, USER_TOKEN, USER_USING2FA, USER_ENABLED) VALUES (N'member2@test.com', 10, '$2a$10$D0yw7uHWgsCbjj.CAuZ8D.hh38aPkEeV5v9iiyyQ7NzbTuMHWPewm', 'member2test', 'Member2', 'Member2', '1968-09-09 00:00:00', '2018-01-12 17:50:22', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'member2@test.com', 327.52, '18a07a66-54ee-49a2-8102-d9377a2fbf9c', 0, 1)
INSERT INTO dbo.USER_DATA(USER_EMAIL, STATUS_ID, USER_PASSWORD, USER_USERNAME, USER_FIRSTNAME, USER_LASTNAME, USER_BIRTHDATE, USER_SIGNIN, USER_DESCRIPTION, USER_LINK_CONTACT, USER_GAZ, USER_TOKEN, USER_USING2FA, USER_ENABLED) VALUES (N'expert2@test.com', 10, '$2a$10$nUfUix6EH6dqOVBf6o2gHeQ0np6EFipxCcmEQ7qu8YbGbMy6GhFLC', 'expert2test', 'Expert2', 'Expert2', '2000-01-01 00:00:00', '2019-06-25 04:47:29', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi', 'expert2@test.com', 70.67, 'b481a522-5452-42c5-b549-a9a0c43e6d3a', 0, 1)
INSERT INTO dbo.USER_DATA(USER_EMAIL, STATUS_ID, USER_PASSWORD, USER_USERNAME, USER_FIRSTNAME, USER_LASTNAME, USER_BIRTHDATE, USER_SIGNIN, USER_DESCRIPTION, USER_LINK_CONTACT, USER_GAZ, USER_TOKEN, USER_USING2FA, USER_ENABLED) VALUES (N'user@test.com', 1, '$2a$10$MnShQU1e8EvJgTYfoh.zdeC1.qIl0G5I.//Fk9d1gROTezggNOcwu', 'usertest', 'User2', 'User2', '1989-12-05 00:00:00', '2020-11-25 13:25:59', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'user@test.com', 0, null, 0, 0)
INSERT INTO dbo.USER_DATA(USER_EMAIL, STATUS_ID, USER_PASSWORD, USER_USERNAME, USER_FIRSTNAME, USER_LASTNAME, USER_BIRTHDATE, USER_SIGNIN, USER_DESCRIPTION, USER_LINK_CONTACT, USER_GAZ, USER_TOKEN, USER_USING2FA, USER_ENABLED) VALUES (N'LuluAlcorn949@example.com', 1, '$2a$10$.w0URjIEVPHuHQRriyYlBeL3X/qDrf8B6Oipx7iqOiUe5COVfVLSm', 'August1990', 'Lulu', 'Alcorn', '1979-10-11 00:00:00', '2019-10-31 03:54:56', 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatu', 'Darleen.Adair@gmail.com', 184.79, '34cde9c9-3744-4e33-97de-310e960dd1c8', 0, 0)
INSERT INTO dbo.USER_DATA(USER_EMAIL, STATUS_ID, USER_PASSWORD, USER_USERNAME, USER_FIRSTNAME, USER_LASTNAME, USER_BIRTHDATE, USER_SIGNIN, USER_DESCRIPTION, USER_LINK_CONTACT, USER_GAZ, USER_TOKEN, USER_USING2FA, USER_ENABLED) VALUES (N'Higdon@nowhere.com', 10, '$2a$10$KM37nGOeKMV0D0aryM..yurEqtWje7.IcXf2RYfhNDwPFGY4YJIEW', 'Rosalyn2026', 'Florene', 'Higdon', '1998-08-12 00:00:00', '2019-07-12 19:13:24', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'Myriam.Abernathy@gmail.com', 173.54 , 'b7d22229-da63-4978-8f5a-ec05034d3625', 0, 1)
INSERT INTO dbo.USER_DATA(USER_EMAIL, STATUS_ID, USER_PASSWORD, USER_USERNAME, USER_FIRSTNAME, USER_LASTNAME, USER_BIRTHDATE, USER_SIGNIN, USER_DESCRIPTION, USER_LINK_CONTACT, USER_GAZ, USER_TOKEN, USER_USING2FA, USER_ENABLED) VALUES (N'Yang@nowhere.com', 10, '$2a$10$nrCGsdWwVTa8GbMpjJTyJudUetVJZgzL7.qEn/BzVWw4zpFJtZzCu', 'Akiko43', 'Ndo', 'Yang', '1949-05-01 00:00:00', '2019-07-04 20:29:40', 'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur', 'Jonah.Rouse@gmail.com', 339.9, '49e96459-812f-47fd-92b3-58f7e5247fd0', 0, 1)
INSERT INTO dbo.USER_DATA(USER_EMAIL, STATUS_ID, USER_PASSWORD, USER_USERNAME, USER_FIRSTNAME, USER_LASTNAME, USER_BIRTHDATE, USER_SIGNIN, USER_DESCRIPTION, USER_LINK_CONTACT, USER_GAZ, USER_TOKEN, USER_USING2FA, USER_ENABLED) VALUES (N'AbigailBowman2@nowhere.com', 10, '$2a$10$4ezCfBhKvgI88ZKJjYihl.KHXP2I/WXqlrD4rIw2ranponzI1W1jq', 'Abigail2', 'Abigail', 'Bowman', '1972-04-04 00:00:00', '2019-12-08 15:48:02', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'Whitney.Dove@gmail.com', 83.65, '1ead310a-215f-43f5-85ee-3f9ea917519c', 0, 1)
INSERT INTO dbo.USER_DATA(USER_EMAIL, STATUS_ID, USER_PASSWORD, USER_USERNAME, USER_FIRSTNAME, USER_LASTNAME, USER_BIRTHDATE, USER_SIGNIN, USER_DESCRIPTION, USER_LINK_CONTACT, USER_GAZ, USER_TOKEN, USER_USING2FA, USER_ENABLED) VALUES (N'DelmaAcevedo@example.com', 11, '$2a$10$/4Wc/KMEmyb9T3veDz6DceIn14EaojHCTQLwp7meJOYiUnXqPAu1q', 'Emerson1962', 'Delma', 'Acevedo', '1967-10-05 00:00:00', '2019-01-28 17:09:08', 'Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id', 'Donnell.Mclean@gmail.com', 396.55, 'c72508fb-af1d-4316-9759-bdd55c920a4e', 0, 0)
INSERT INTO dbo.USER_DATA(USER_EMAIL, STATUS_ID, USER_PASSWORD, USER_USERNAME, USER_FIRSTNAME, USER_LASTNAME, USER_BIRTHDATE, USER_SIGNIN, USER_DESCRIPTION, USER_LINK_CONTACT, USER_GAZ, USER_TOKEN, USER_USING2FA, USER_ENABLED) VALUES (N'Dewayne_Penny@example.com', 11, '$2a$10$1LqNn0X0vpI5w9ZOprKape6Y/QlSB7TOFwbUHXOQowjWT8lHLrbMK', 'Seymour97', 'Penny', 'Dewayne', '1975-02-08 00:00:00', '2020-11-15 10:59:14', 'Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.', 'arielle.adamson@gmail.com', 272.59,  '1c8b55b3-cbab-4f9d-85c2-962668ba9e2c', 0, 0)



INSERT INTO dbo.STRATEGY(USER_EMAIL, STATUS_ID, STRATEGY_LABEL, STRATEGY_DESCRIPTION, STRATEGY_SYMBOL1, STRATEGY_SYMBOL2, STRATEGY_PRIME, STRATEGY_ICON, STRATEGY_CREATION_DATE, STRATEGY_UPDATE_DATE)
VALUES ('test@test.com', 3, 'Strategy 1', 'Gaia is a new strategic approach, using the latest Kryll blocks. Very effective in bear market and bull market. Do backtest and give it a try, you''ll be surprised.
Gaia work also on other alts like KCS/USDT, GNT/ETH, NANO/BTC, ATOM/BNB, ICX/USDT, ICX/BNB and more.
Keep in touche, ', 'BTC', 'LTC', 2.07, '01', '2020-02-22 11:36:58', '2020-08-09 00:39:46')
INSERT INTO dbo.STRATEGY(USER_EMAIL, STATUS_ID, STRATEGY_LABEL, STRATEGY_DESCRIPTION, STRATEGY_SYMBOL1, STRATEGY_SYMBOL2, STRATEGY_PRIME, STRATEGY_ICON, STRATEGY_CREATION_DATE, STRATEGY_UPDATE_DATE)
VALUES ('test@test.com', 5, 'Strategy 2', 'Gaia peut maintenant être démarré avec n''importe quelle montant sur n''importe quelle paire.
- La stratégie incorpore un nouveau système de détection bullsh pour rachat durant les période haussière afin d''amélioré la rentabilité.
Gaïa est une nouvelle approche stratégique, utilisant les derniers blocs Kryll. Fonctionne a marveille en marché baissier et marché haussier. Faite vos backtests et essayer Gaia.
Gaia fonctionne aussi sur d''autre alts comme KCS/USDT, GNT/ETH, NANO/BTC, ATOM/BNB, ICX/USDT, ICX/BNB and et bien plus.',
        'BTC', 'Libra', 10.44, '02', '2020-04-29 12:49:22', '2020-09-08 20:12:42')
INSERT INTO dbo.STRATEGY(USER_EMAIL, STATUS_ID, STRATEGY_LABEL, STRATEGY_DESCRIPTION, STRATEGY_SYMBOL1, STRATEGY_SYMBOL2, STRATEGY_PRIME, STRATEGY_ICON, STRATEGY_CREATION_DATE, STRATEGY_UPDATE_DATE)
VALUES ('AbigailBowman2@nowhere.com', 1, 'Strategy 3', 'The strategy has been updated for the following reason

1. After seeing that LINK/BTC was not buying in the bull market I started working on it.
2. A volume block has been implemented that detects the bull market.
3. Luckily, after hundreds of tests, this block does not affect the bear market at all.
4. Remember to stop and start the strategy again.

This strategy is a good example of trading in a heterogeneous market. It exploits golden and dead crosses between a fast EMA, SMA, volume and bollinger to detect short term entry points.',
        'BTC', 'BNB', 10.44, '03', '2020-04-29 12:49:22', '2020-09-08 20:12:42')
INSERT INTO dbo.STRATEGY(USER_EMAIL, STATUS_ID, STRATEGY_LABEL, STRATEGY_DESCRIPTION, STRATEGY_SYMBOL1, STRATEGY_SYMBOL2, STRATEGY_PRIME, STRATEGY_ICON, STRATEGY_CREATION_DATE, STRATEGY_UPDATE_DATE)
VALUES ('Yang@nowhere.com', 1, 'Strategy 4', 'Advices :
- Starting : always start in Full USDT, never All In - If you want to use it strategy to all you $BTC bag, never launch in one time - Use different moment : TOP / BOTTOM / RANGE
- Testing : don''t test the strategy on a strict BEAR or bull TREND, if you use it, stay calm, it''s a yearly strategy able to play BEAR + BULL - This one bought the COVID Crisis bottom.
- Checking : our choice is to play without SL to avoid wick - If we see a massive drop or a large bear market without relief ... strategy could block - For the moment, on long term, Strategy never block, except if you launch it at TOP

DISCLAIMER : Not Financial Advice - Use DCA or « Dollar Cost Averaging » - Actually at a Top, don''t be crazy', 'BTC',
        'ETH', 7.94, '04', '2019-09-25 00:01:56', '2019-11-02 11:00:53')
INSERT dbo.STRATEGY(USER_EMAIL, STATUS_ID, STRATEGY_LABEL, STRATEGY_DESCRIPTION, STRATEGY_SYMBOL1, STRATEGY_SYMBOL2, STRATEGY_PRIME, STRATEGY_ICON, STRATEGY_CREATION_DATE, STRATEGY_UPDATE_DATE)
VALUES ('expert@test.com', 6, 'Strategy 5', 'This strategy is adapted for ETH-USDT pair on Binance Spot. If you would like to use it with other pairs or other exchanges, I suggest running several back-tests before starting live session.
Maya is a swing strategy efficient on long term (at least 3 months). You can run full USDT, full ETH, 50/50 or whatever you want, depending on the market evolution.
MACD, EMA, VOLUME indicators are used to detect bullish market for buy entries. Some ICHIMOKU conditions are used to switch from a block to another. Take Profits is triggered in different ways: Trailing Sell to secure profits or indicators detection. Stop Loss are executed on indicators detection, not on % of price dump, so it could be different depending on the market evolution.
During Bullish market or strong dump, the strategy is switching into the Accumulation Mode, small buy orders are placed to be sold on price pump. A Telegram group is available for questions and suggestions @mayabotstrategy do not hesitate to join us.
Cette stratégie est adaptée pour la paire ETH-USDT sur Binance Spot. Si vous souhaitez l’utiliser sur d’autres paires ou sur d’autres échanges, je vous invite à faire des back-tests avant de démarrer des sessions live.',
        'BTC', 'ETH', 5.68, '05', '2019-10-24 01:47:59', '2020-09-24 23:48:34')
INSERT INTO dbo.STRATEGY(USER_EMAIL, STATUS_ID, STRATEGY_LABEL, STRATEGY_DESCRIPTION, STRATEGY_SYMBOL1, STRATEGY_SYMBOL2, STRATEGY_PRIME, STRATEGY_ICON, STRATEGY_CREATION_DATE, STRATEGY_UPDATE_DATE)
VALUES ('expert@test.com', 5, 'Strategy 6', 'This strategy does not trade every day, on the contrary, it seeks to make the most relevant trades possible and therefore as often as possible. Like any bot this one sometimes makes mistakes. You can lose money. This strategy can lead to very large drawdowns over long periods of time. The strategy may not trade for long periods (max 15 days) -> This is normal. When you launch the strategy it can wait between 1 day and up to 10 days to start. It does not seek to make the record of the number of trades, on the contrary it seeks to be efficient.
LIFE IS TOO SHORT is a bot developed specifically for the BTC / USDT pair on Binance. I advise you to always start in Full USDT (Minimum 300 USDT) This bot has been designed to trade on a minimum of 3 confirmations. It has its SETUP on confirmations and will not deviate from it.
The bot works for both Bullish and Bearish markets. On Bull Market, he will try to exit as late as possible and can hold a trade open for several days. On the bear market, it will invest by step by accumulating more and more BTC. Average frequency of trading: 1 day out of 3. But the strategy may not start a trade over longer periods (see backtests)
If you are looking for a strategy that trades daily, this Bot is not for you. The accumulation mode can lead to significant drowdown over short periods of time. This Bot works on confirmation, it will not be able to buy every time at the lowest, nor sell at the highest, but will constantly seek confirmations for its SETUP in order to maximize the gains in the medium / long term.
I invite you to backtest the Bot in order to better understand its philosophy.
Thank you again for choosing this strategy.', 'BTC', 'BNB', 13.95, '06', '2020-09-17 16:12:28', '2020-05-07 15:19:41')
INSERT INTO dbo.STRATEGY(USER_EMAIL, STATUS_ID, STRATEGY_LABEL, STRATEGY_DESCRIPTION, STRATEGY_SYMBOL1, STRATEGY_SYMBOL2, STRATEGY_PRIME, STRATEGY_ICON, STRATEGY_CREATION_DATE, STRATEGY_UPDATE_DATE)
VALUES ('expert@test.com', 5, 'Strategy 7', 'Ethereum to Binance. Version 5 available! ATTENTION! Taking into account all the movements from September 5, 2017 to the present, you will obtain a profit of ⭐ 40,055.99% ⭐. You can enter the strategy with USDT or BTC (However, I recommend that you start with USDT). The uptrend strategy increases USDT and in downtrend it increases BTC. To test the strategy: First click on "Pick and use" Second click on the button: "Backtest". Third, observe that the option: "binance" is found, select the currency "BTC / USDT", activate the option "Pro mode" and then select the start date: 09/05/2017 and the end date: "current date ". Fourth press the "Test" button. Operation: The strategy takes advantage of all the rises in an uptrend, it is also designed to avoid downtrends, it is also prepared to catch whales. Multiple variables are analyzed for both buying and selling. Note: Given this dark stage of pandemic for so many people in the world. I want to do my part to overcome this crisis by doing my bit by offering this strategy for free temporarily. Telegram: t.me/tothemoonkryll Note: The strategy has a new module that, when launched, generates a quick purchase and a stop loss is placed. Then the normal operation of the strategy cycle begins.
(Français) Version 5 disponible! ATTENTION! En tenant compte de tous les mouvements du 5 septembre 2017 à nos jours, vous obtiendrez un bénéfice de 40,055.99%. Vous pouvez entrer la stratégie avec USDT ou BTC (Cependant, je vous recommande de commencer par USDT). La stratégie dans une tendance haussière augmente l''USDT et dans une tendance baissière, elle augmente le BTC. Pour tester la stratégie: Cliquez d''abord sur «Installer». Deuxième clic sur le bouton: «Backtest». Troisièmement, observez que l''option: "binance" est trouvée, sélectionnez la devise "BTC / USDT", activez l''option "Mode pro" puis sélectionnez la date de début: 09/05/2017 et la date de fin: "date du jour ". Quatrièmement, appuyez sur le bouton "Test". Fonctionnement: La stratégie profite de toutes les hausses dans une tendance haussière, elle est également conçue pour éviter les tendances à la baisse, elle est également prête à attraper des baleines. Plusieurs variables sont analysées à la fois pour l''achat et la vente. Remarque: Compte tenu de cette sombre étape de la pandémie pour tant de personnes dans le monde. Je veux faire ma part pour surmonter cette crise en faisant ma part en proposant cette stratégie gratuitement temporairement.',
        'ETH', 'BNB', 6.28, '07', '2019-10-25 14:41:44', '2019-05-18 16:04:48')
INSERT INTO dbo.STRATEGY(USER_EMAIL, STATUS_ID, STRATEGY_LABEL, STRATEGY_DESCRIPTION, STRATEGY_SYMBOL1, STRATEGY_SYMBOL2, STRATEGY_PRIME, STRATEGY_ICON, STRATEGY_CREATION_DATE, STRATEGY_UPDATE_DATE)
VALUES ('expert@test.com', 1, 'Strategy 8', 'Lulu BitCoin to Ethereum :warning::warning:nota bene: diversifying, because diversification is the secret to success Nota bene 2 this is a long term strategy which means at least 1 month if you count on a result after 12 hours of launch I invite you to go to the casino and make a martingale :warning::warning:
BT pairs over 3 months make your choice efficient scalping/intraday strategy on long term link/btc 376000% from its binance listing efficient also on multi-pair spreadsheet table attached there is no stop loss all this by indicator LEER TODO EL CAMINO A TRAVÉS DE La diversificación es el secreto del éxito Nota bene 2 es una estrategia a largo plazo, lo que significa al menos 1 mes si cuentas con un resultado después de 12 horas de lanzamiento Te invito a ir al casino y hacer una martingala :warning::warning:
Los pares de BT de más de 3 meses hacen su elección. eficiente estrategia de escalada/interdía en el enlace a largo plazo/btc 376000% desde su binancia listado eficiente también en la tabla de hoja de cálculo multipar adjunta
no hay pérdida de parada, todo esto por indicador.', 'BTC', 'ETH', 6.29, '08', '2019-04-02 15:21:53',
        '2020-04-30 05:45:52')
INSERT INTO dbo.STRATEGY(USER_EMAIL, STATUS_ID, STRATEGY_LABEL, STRATEGY_DESCRIPTION, STRATEGY_SYMBOL1, STRATEGY_SYMBOL2, STRATEGY_PRIME, STRATEGY_ICON, STRATEGY_CREATION_DATE, STRATEGY_UPDATE_DATE)
VALUES ('expert2@test.com', 6, 'Strategy  9', 'BTC Never Dies is the Strategy to survive on Bear & Bull Market Protect capital & use our BTC strategy on Long Term with DCA Since Binance Listing BTC/USDT, you can accumulate a x 21 Bag of BTC Don''t be afraid by a pullback or bear market, our strategy accumulate on long term We got no SL due to BTC hard wick & because we are BTC Maximalist Market making waves - Since 2017, strategy never blocked, otherwise, we will relaunch - It''s possible - This Strategy could be great for BTC Long Term Holder to accumulate more $BTC
- $BTC seems crazy, our V2 (x 21 Strategy) is great but update a V3 (x16 Strategy) du to market
Advices :
- Starting : always start in Full USDT, never All In - If you want to use it strategy to all you $BTC bag, never launch in one time - Use different moment : TOP / BOTTOM / RANGE
- Testing : don''t test the strategy on a strict BEAR or bull TREND, if you use it, stay calm, it''s a yearly strategy able to play BEAR + BULL - This one bought the COVID Crisis bottom.
- Checking : our choice is to play without SL to avoid wick - If we see a massive drop or a large bear market without relief ... strategy could block - For the moment, on long term, Strategy never block, except if you launch it at TOP

DISCLAIMER : Not Financial Advice - Use DCA or « Dollar Cost Averaging » - Actually at a Top, don''t be crazy', 'BTC',
        'XRP', 5.12, '09', '2020-01-19 16:26:08', '2020-03-07 04:41:58')
INSERT INTO dbo.STRATEGY(USER_EMAIL, STATUS_ID, STRATEGY_LABEL, STRATEGY_DESCRIPTION, STRATEGY_SYMBOL1, STRATEGY_SYMBOL2, STRATEGY_PRIME, STRATEGY_ICON, STRATEGY_CREATION_DATE, STRATEGY_UPDATE_DATE)
VALUES ('expert2@test.com', 1, 'Strategy 10', 'Dah tlhingan hol mu ghom a dalegh.  Qawhaqvam chenmohlu di wiqipe diya ohvad ponglu.  Ach jinmolvamvad Saghbe law tlhingan hol, dis, oh mevmohlu.
Ach dis jar wa mahcha dich wikia jinmoldaq vihta.  Hov lengvad chenmohlu tlhingan hol e ej dah oh ghojtah ghot law.  Qapbej holvam wicha meh, qawhaqvam chenmohlu .
Tahjaj wo, tahjaj hol Sov qawhaq tlhab oh ej ghitlhmey diqonmeh tlhingan hol wilo.  Ghitlhmey chenmohlah ej chohlah tlhingan hol jatlhlahbogh hoch ghotpu e.
Wej tin Sov qawhaqvam, ach ghurli e witul.  Dah ghitlhmey ngas.  Vay daghel danehchugh, vaj tachdaq maghom.', 'BTC',
        'ETH', 7.37, '10', '2020-08-14 19:10:22', '2020-02-07 02:13:49')
INSERT INTO dbo.STRATEGY(USER_EMAIL, STATUS_ID, STRATEGY_LABEL, STRATEGY_DESCRIPTION, STRATEGY_SYMBOL1, STRATEGY_SYMBOL2, STRATEGY_PRIME, STRATEGY_ICON, STRATEGY_CREATION_DATE, STRATEGY_UPDATE_DATE)
VALUES ('expert2@test.com', 5, 'Strategy 11', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'BTC',
        'EOS', 13.9, '01', '2019-08-27 18:22:13', '2019-06-26 03:08:12')
INSERT INTO dbo.STRATEGY(USER_EMAIL, STATUS_ID, STRATEGY_LABEL, STRATEGY_DESCRIPTION, STRATEGY_SYMBOL1, STRATEGY_SYMBOL2, STRATEGY_PRIME, STRATEGY_ICON, STRATEGY_CREATION_DATE, STRATEGY_UPDATE_DATE)
VALUES ('expert2@test.com', 6, 'Strategy 12', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        'BTC', 'XLM', 2.6, '02', '2019-01-19 11:17:17', '2020-07-24 22:23:42')


INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('test@test.com', 'BTC', 108.46)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('test@test.com', 'LTC', 117561.27)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('test@test.com', 'BNB', 5.13)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('test@test.com', 'ETH', 28117.68)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('test@test.com', 'XMR', 29872.11)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('expert@test.com', 'BTC', 196.03)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('expert@test.com', 'LTC', 7.29)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('expert@test.com', 'ETH', 141678.69)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('expert@test.com', 'XRP', 82734.26)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('expert@test.com', 'EOS', 8.78)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('expert@test.com', 'BNB', 100503.59)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('expert2@test.com', 'BTC', 2516.54)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('expert2@test.com', 'ETH', 6763.94)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('expert2@test.com', 'BNB', 192192.8)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('expert2@test.com', 'XLM', 146044.51)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('expert2@test.com', 'XRP', 77768.09)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('member@test.com', 'BTC', 43971.82)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('member@test.com', 'ETH', 14933.04)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('member@test.com', 'EOS', 128436.92)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('member@test.com', 'BNB', 163175.93)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('member@test.com', 'XRP', 29453.15)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('LuluAlcorn949@example.com', 'ETH', 157844.37)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('LuluAlcorn949@example.com', 'BTC', 165770.09)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('Higdon@nowhere.com', 'ETH', 186209.12)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('Higdon@nowhere.com', 'BTC', 161955.35)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('Higdon@nowhere.com', 'EOS', 104813.16)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('Higdon@nowhere.com', 'XRP', 11397.89)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('Yang@nowhere.com', 'BTC', 179789.36)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('Yang@nowhere.com', 'ETH', 66773.52)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('Yang@nowhere.com', 'BNB', 140775.08)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('Yang@nowhere.com', 'XRP', 137575.46)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('AbigailBowman2@nowhere.com', 'BNB', 1.12)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('AbigailBowman2@nowhere.com', 'BTC', 0.53)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('AbigailBowman2@nowhere.com', 'ETH', 117899.92)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('DelmaAcevedo@example.com', 'BTC', 9082.26)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('DelmaAcevedo@example.com', 'EOS', 9)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('DelmaAcevedo@example.com', 'BNB', 185617.74)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('DelmaAcevedo@example.com', 'ETH', 98847.38)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('DelmaAcevedo@example.com', 'VTC', 196574.08)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('Dewayne_Penny@example.com', 'ETH', 90815.27)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('Dewayne_Penny@example.com', 'BTC', 96250.85)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('Dewayne_Penny@example.com', 'BNB', 30323.63)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('Dewayne_Penny@example.com', 'XRP', 102905.91)
INSERT INTO dbo.WALLET(USER_EMAIL, WALLET_BALANCE_SYMBOL, WALLET_BALANCE_TOTAL) VALUES ('Dewayne_Penny@example.com', 'EOS', 5.11)



INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (3, 9, 'test@test.com', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-12-07 16:50:15', '2020-04-15 22:54:44', 'BA1C:4377:E940:8CB:6285:0D76:99:A4AD')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (9, 9, 'test@test.com', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-04-12 02:21:29', '2019-11-21 22:39:33', '8E3E:3D10:F:16C:6:29C8:ECEF:BBBA')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (1, 3, 'Yang@nowhere.com', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-10-14 20:36:08', '2019-11-09 03:02:51', '6900:0E24:E:7698:4993:EDC:4F9:00BE')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (7, 9, 'LuluAlcorn949@example.com', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-11-24 08:15:36', '2020-05-10 18:05:39', 'E4BB:B9:B097:20DB:0:E19D:47DB:D3E')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (3, 8, 'expert@test.com', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-01-03 20:39:52', '2019-08-04 14:19:31', '44:1C:7CDE:6CD4:A2:2:344B:0')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (3, 1, 'AbigailBowman2@nowhere.com', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-05-20 18:54:26', '2020-03-29 10:45:56', 'E22A:0E7E:7D84:7:F1B:7E76:7E0F:B')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (2, 1, 'expert@test.com', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-10-23 07:41:27', '2019-03-08 15:01:53', '1FF0:A7F0:10:6C1:2E1E:4DDD:18A2:2CFF')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (8, 7, 'member@test.com', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-02-22 18:51:47', '2019-06-13 15:51:09', '2E9:D1:112E:BA:C90A:7:65D3:3')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (1, 5, 'expert2@test.com', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-03-13 05:09:12', '2020-11-02 22:20:39', '2:9FC:31:3:EFD2:68EE:ECCD:4AC4')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (9, 3, 'expert@test.com', 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-06-14 21:46:51', '2019-09-24 16:27:05', 'FBDA:35:EE:C8EE:A52:CFD0:31:8BCF')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (7, 6, 'member2@test.com', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-05-17 18:08:30', '2019-02-28 11:29:48', 'DD7C:E4D5:B8F1:1451:9DFB:5352:3E05:78F9')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (3, 4, 'Yang@nowhere.com', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-04-25 06:41:06', '2019-03-15 07:52:06', '4B46:62:6A:C:DBD1:5BD:5:8')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (2, 5, 'AbigailBowman2@nowhere.com', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-03-30 15:04:48', '2019-08-07 14:48:40', '0B86:DF06:B:3BEB:84:5A45:1189:CF')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (6, 8, 'expert@test.com', 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-09-30 02:35:07', '2019-03-06 16:51:01', 'B721:5:7AB:D:8AF1:6A8D:6:18')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (8, 7, 'expert2@test.com', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-11-11 08:42:48', '2019-12-14 02:49:00', '5297:BE4A:0FEB:8C:37F:661C:0FA1:D')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (2, 3, 'member@test.com', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-03-14 23:39:14', '2019-05-12 16:28:27', 'B3B:823:E5BE:1AD:AA8B:F:6F:F')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (5, 3, 'LuluAlcorn949@example.com', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-04-04 18:52:39', '2019-12-08 05:20:25', 'E:14D:0FED:6:BFE:DC51:3:AB')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (7, 7, 'member2@test.com', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-05-17 01:37:50', '2019-12-23 20:02:25', '739E:CFCF:22:D3F:9CD:D4AF:C:6AB9')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (2, 6, 'member@test.com', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-11-12 18:01:25', '2020-02-11 09:26:36', 'C73F:AB4B:9:39D:C:7F:A:F7')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (2, 1, 'member@test.com', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-11-16 19:30:31', '2020-06-06 02:05:20', 'B642:F:EA82:F:6A:374:9BC8:6E85')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (7, 5, 'member2@test.com', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-08-02 01:33:19', '2019-07-12 02:27:49', '4FCA:6A5:895:843B:7E8B:5:A:E3E7')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (1, 4, 'expert2@test.com', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-07-08 14:09:20', '2020-04-24 09:16:25', 'D32D:5B52:5FB3:AE:D45:8238:A:EDEA')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (5, 7, 'expert2@test.com', 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-08-24 01:56:15', '2019-07-16 04:28:32', 'B:7ED8:2C:E5:E:2DCA:A:8F41')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (6, 9, 'member@test.com', 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-08-10 17:43:15', '2020-09-23 20:49:10', '8B9:FA:E:0F:E6CB:1DD:BCA7:1A74')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (2, 1, 'Yang@nowhere.com', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-11-21 05:19:46', '2020-02-07 15:13:08', '64:FEF:90B9:11C:383B:328:A:FBEA')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (5, 6, 'member@test.com', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-08-12 15:15:24', '2020-01-11 21:52:29', 'F8BA:A:C78F:C5AA:EFD9:C:6F:2BA1')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (3, 3, 'expert@test.com', 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-05-23 04:28:46', '2019-04-13 23:52:21', '5C86:B0:B:A27D:FDD0:CAD4:5:1F')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (6, 2, 'Dewayne_Penny@example.com', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-07-01 13:10:28', '2019-05-13 02:55:26', 'F49F:A9B:8DCD:DD0F:DF0E:9090:E4:FCF7')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (6, 8, 'Yang@nowhere.com', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-02-21 14:37:41', '2019-04-25 21:11:12', '6:7DC6:F338:0:A636:D1B0:E43A:96D5')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (1, 8, 'Yang@nowhere.com', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-02-23 00:45:10', '2020-05-10 13:33:50', 'F7CC:DB:9BF4:24F0:49F1:9BEC:9:0AA2')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (4, 1, 'member@test.com', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-12-05 00:25:45', '2019-10-22 06:31:59', '1AFF:6A1D:E:5FDC:0A0D:2611:68:8CBD')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (9, 6, 'Higdon@nowhere.com', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-06-13 20:03:36', '2019-03-20 22:49:39', 'BCDA:CDC9:F:A:D82:9:4:D711')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (2, 9, 'DelmaAcevedo@example.com', 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-12-13 22:08:59', '2020-06-07 16:32:30', 'C7A:EE43:FAB:3D8:A0EE:FC:5375:8')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (4, 2, 'AbigailBowman2@nowhere.com', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-03-29 13:25:33', '2020-07-14 20:47:56', 'FDBF:8462:23E1:E42A:63EC:5EA7:1:FCF1')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (3, 9, 'DelmaAcevedo@example.com', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-01-27 01:07:13', '2020-09-05 16:16:28', '0F:BDC6:B1FB:C036:01:6075:C7F:C')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (5, 8, 'DelmaAcevedo@example.com', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-09-19 17:32:42', '2019-12-25 22:23:31', 'AE:5A73:EA85:40EC:0763:1792:7A:FCCA')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (8, 4, 'member2@test.com', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-05-03 16:15:55', '2020-10-18 09:06:23', 'ACE9:DF1F:FBC:6:F:3CA9:DEAF:2')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (8, 8, 'Dewayne_Penny@example.com', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-05-16 21:07:05', '2020-03-22 22:17:17', '0B:2DEF:22FD:C:92A:E:071C:AB8')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (7, 5, 'member@test.com', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-07-20 05:01:19', '2020-08-21 12:51:17', 'DB8F:63:1A91:0:A5:FEC4:F14F:A87D')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (5, 1, 'expert@test.com', 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-06-27 20:19:10', '2019-02-04 15:16:25', '0A7B:7:FE5:F:CE21:A:E2CC:1F')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (7, 8, 'Dewayne_Penny@example.com', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-07-27 05:43:47', '2019-11-09 18:14:39', 'EA92:0692:14:31C:C6:C:F20E:77')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (6, 5, 'Yang@nowhere.com', 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-07-15 09:50:06', '2020-05-03 07:57:06', 'D5B8:1CF2:9:D038:8:6:6:8')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (2, 7, 'expert2@test.com', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-09-28 06:54:25', '2020-08-17 09:42:44', '216B:B422:CBFD:E652:A3:FBFF:EBDE:D')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (9, 8, 'LuluAlcorn949@example.com', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-03-18 07:05:47', '2019-04-16 08:38:48', '1F3:8B:B:84:A:C:F:BDA')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (4, 3, 'member2@test.com', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-12-11 20:19:36', '2019-08-09 16:50:12', '44A:E:8:E81A:8:9100:C308:9')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (7, 4, 'Yang@nowhere.com', 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-11-18 14:51:46', '2019-01-13 09:56:27', '3F3D:C:6:CBF2:031A:F965:D:95')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (8, 5, 'AbigailBowman2@nowhere.com', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-06-10 00:36:56', '2020-01-11 19:54:52', 'CFD1:9FC:C:96B5:C3A8:F4BB:A24A:B7')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (7, 5, 'AbigailBowman2@nowhere.com', 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-06-26 09:27:13', '2019-04-17 17:57:14', 'EADD:A:BFEA:A4D:FAF:C94A:DFDA:17E9')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (6, 3, 'expert2@test.com', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2019-01-29 19:29:51', '2019-08-07 18:55:10', 'BADB:6B85:44:90A1:6:B295:87CD:CF6C')
INSERT INTO dbo.COMMENT(STRATEGY_ID, STATUS_ID, USER_EMAIL, COMMENT_SCORE, COMMENT_DESCRIPTION, COMMENT_CREATION_DATE, COMMENT_UPDATE_DATE, COMMENT_MEMBER_IP) VALUES (1, 2, 'Yang@nowhere.com', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper eget duis at tellus at urna condimentum mattis pellentesque. Nunc aliquet bibendum enim facilisis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.', '2020-08-07 21:22:26', '2020-09-25 12:47:44', '4:1A45:55CA:E:D:DBBB:A5F5:0EED')


INSERT INTO dbo.PROFIL_FONCTION(PROFIL_ID, FONCTION_ID) VALUES (1, 1)
INSERT INTO dbo.PROFIL_FONCTION(PROFIL_ID, FONCTION_ID) VALUES (2, 2)
INSERT INTO dbo.PROFIL_FONCTION(PROFIL_ID, FONCTION_ID) VALUES (3, 4)
INSERT INTO dbo.PROFIL_FONCTION(PROFIL_ID, FONCTION_ID) VALUES (4, 2)
INSERT INTO dbo.PROFIL_FONCTION(PROFIL_ID, FONCTION_ID) VALUES (5, 4)
INSERT INTO dbo.PROFIL_FONCTION(PROFIL_ID, FONCTION_ID) VALUES (3, 5)



INSERT INTO dbo.TRADE(USER_EMAIL, STATUS_ID, TRADE_PLATFORM, TRADE_AMOUNT_SYMBOL1, TRADE_AMOUNT_SYMBOL2, TRADE_PAIR_LIMIT, TRADE_AMOUNT_LIMIT, TRADE_SYMBOL, TRADE_CLIENTORDERLIST, TRADE_TRANSACTIME, TRADE_PRICE, TRADE_ORIGQTY, TRADE_CUMMULATIVEQUOTEQTY, TRADE_STATUS, TRADE_TIMEINFORCE, TRADE_TYPE, TRADE_SIDE, TRADE_CREATION_DATE, TRADE_UPDATE_DATE) VALUES ('test@test.com',	                1, 'Binance', '10',  '10', '16300',	'16250', 'BTCXMR', '24695', 1605865234341, '16277', '0.000123',	'1', 'NEW', 'GTC', 'LIMIT',         'BUY',  '2019-03-04 03:36:03', '2019-07-12 09:40:33')
INSERT INTO dbo.TRADE(USER_EMAIL, STATUS_ID, TRADE_PLATFORM, TRADE_AMOUNT_SYMBOL1, TRADE_AMOUNT_SYMBOL2, TRADE_PAIR_LIMIT, TRADE_AMOUNT_LIMIT, TRADE_SYMBOL, TRADE_CLIENTORDERLIST, TRADE_TRANSACTIME, TRADE_PRICE, TRADE_ORIGQTY, TRADE_CUMMULATIVEQUOTEQTY, TRADE_STATUS, TRADE_TIMEINFORCE, TRADE_TYPE, TRADE_SIDE, TRADE_CREATION_DATE, TRADE_UPDATE_DATE) VALUES ('test@test.com',					5, 'Binance', '10', '10', '16300',  '16250', 'LTCBNB', '24695', 1605851300603, '16277',	'16277',	'1', 'NEW', 'FOK', 'STOP_LOSS',	    'SELL', '2020-01-28 21:21:03', '2019-12-22 11:08:30')
INSERT INTO dbo.TRADE(USER_EMAIL, STATUS_ID, TRADE_PLATFORM, TRADE_AMOUNT_SYMBOL1, TRADE_AMOUNT_SYMBOL2, TRADE_PAIR_LIMIT, TRADE_AMOUNT_LIMIT, TRADE_SYMBOL, TRADE_CLIENTORDERLIST, TRADE_TRANSACTIME, TRADE_PRICE, TRADE_ORIGQTY, TRADE_CUMMULATIVEQUOTEQTY, TRADE_STATUS, TRADE_TIMEINFORCE, TRADE_TYPE, TRADE_SIDE, TRADE_CREATION_DATE, TRADE_UPDATE_DATE) VALUES ('test@test.com',					6, 'Binance', '10', '10', '16300',	'16250', 'BNBETH', '24695', 1605854177101, '16277',	'16277',	'1', 'NEW', 'IOC', 'TAKE_PROFIT',	'SELL', '2020-06-06 07:15:26', '2019-08-03 11:22:48')
INSERT INTO dbo.TRADE(USER_EMAIL, STATUS_ID, TRADE_PLATFORM, TRADE_AMOUNT_SYMBOL1, TRADE_AMOUNT_SYMBOL2, TRADE_PAIR_LIMIT, TRADE_AMOUNT_LIMIT, TRADE_SYMBOL, TRADE_CLIENTORDERLIST, TRADE_TRANSACTIME, TRADE_PRICE, TRADE_ORIGQTY, TRADE_CUMMULATIVEQUOTEQTY, TRADE_STATUS, TRADE_TIMEINFORCE, TRADE_TYPE, TRADE_SIDE, TRADE_CREATION_DATE, TRADE_UPDATE_DATE) VALUES ('test@test.com',					1, 'Binance', '10', '10', '16300',	'16250', 'ETHBTC', '24695', 1605851300601, '16277',	'16277',	'1', 'NEW', 'IOC', 'LIMIT_MAKER',   'BUY',	'2019-03-12 23:11:24', '2019-02-03 05:38:03')
INSERT INTO dbo.TRADE(USER_EMAIL, STATUS_ID, TRADE_PLATFORM, TRADE_AMOUNT_SYMBOL1, TRADE_AMOUNT_SYMBOL2, TRADE_PAIR_LIMIT, TRADE_AMOUNT_LIMIT, TRADE_SYMBOL, TRADE_CLIENTORDERLIST, TRADE_TRANSACTIME, TRADE_PRICE, TRADE_ORIGQTY, TRADE_CUMMULATIVEQUOTEQTY, TRADE_STATUS, TRADE_TIMEINFORCE, TRADE_TYPE, TRADE_SIDE, TRADE_CREATION_DATE, TRADE_UPDATE_DATE) VALUES ('expert@test.com',		        5, 'Binance', '10', '10', '16300',	'16250', 'XMRLTC', '24695', 1605852446568, '16277',	'16277',	'1', 'NEW', 'GTO', 'LIMIT',		    'SELL', '2019-10-08 12:34:55', '2019-10-30 13:23:09')
INSERT INTO dbo.TRADE(USER_EMAIL, STATUS_ID, TRADE_PLATFORM, TRADE_AMOUNT_SYMBOL1, TRADE_AMOUNT_SYMBOL2, TRADE_PAIR_LIMIT, TRADE_AMOUNT_LIMIT, TRADE_SYMBOL, TRADE_CLIENTORDERLIST, TRADE_TRANSACTIME, TRADE_PRICE, TRADE_ORIGQTY, TRADE_CUMMULATIVEQUOTEQTY, TRADE_STATUS, TRADE_TIMEINFORCE, TRADE_TYPE, TRADE_SIDE, TRADE_CREATION_DATE, TRADE_UPDATE_DATE) VALUES ('expert@test.com',               1, 'Binance', '10', '10', '16300',	'16250', 'LTCBTC', '24695', 1605850323601, '16277',	'16277',	'1', 'NEW', 'GTO', 'MARKET',		'SELL', '2020-05-13 22:21:26', '2020-10-24 17:11:33')
INSERT INTO dbo.TRADE(USER_EMAIL, STATUS_ID, TRADE_PLATFORM, TRADE_AMOUNT_SYMBOL1, TRADE_AMOUNT_SYMBOL2, TRADE_PAIR_LIMIT, TRADE_AMOUNT_LIMIT, TRADE_SYMBOL, TRADE_CLIENTORDERLIST, TRADE_TRANSACTIME, TRADE_PRICE, TRADE_ORIGQTY, TRADE_CUMMULATIVEQUOTEQTY, TRADE_STATUS, TRADE_TIMEINFORCE, TRADE_TYPE, TRADE_SIDE, TRADE_CREATION_DATE, TRADE_UPDATE_DATE) VALUES ('expert@test.com',	            6, 'Binance', '10', '10', '16300',	'16250', 'EOSBTC', '24695', 1605850300602, '16277',	'16277',	'1', 'NEW', 'FOK', 'STOP_LOSS',	    'SELL', '2020-03-23 21:44:13', '2019-04-02 11:32:15')
INSERT INTO dbo.TRADE(USER_EMAIL, STATUS_ID, TRADE_PLATFORM, TRADE_AMOUNT_SYMBOL1, TRADE_AMOUNT_SYMBOL2, TRADE_PAIR_LIMIT, TRADE_AMOUNT_LIMIT, TRADE_SYMBOL, TRADE_CLIENTORDERLIST, TRADE_TRANSACTIME, TRADE_PRICE, TRADE_ORIGQTY, TRADE_CUMMULATIVEQUOTEQTY, TRADE_STATUS, TRADE_TIMEINFORCE, TRADE_TYPE, TRADE_SIDE, TRADE_CREATION_DATE, TRADE_UPDATE_DATE) VALUES ('expert2@test.com',         	    1, 'Binance', '10', '10', '16300',	'16250', 'ETHBTC', '24695', 1605855177101, '16277',	'16277',	'1', 'NEW', 'IOC', 'MARKET',		'BUY',	'2019-05-14 13:35:19', '2019-12-04 23:35:54')
INSERT INTO dbo.TRADE(USER_EMAIL, STATUS_ID, TRADE_PLATFORM, TRADE_AMOUNT_SYMBOL1, TRADE_AMOUNT_SYMBOL2, TRADE_PAIR_LIMIT, TRADE_AMOUNT_LIMIT, TRADE_SYMBOL, TRADE_CLIENTORDERLIST, TRADE_TRANSACTIME, TRADE_PRICE, TRADE_ORIGQTY, TRADE_CUMMULATIVEQUOTEQTY, TRADE_STATUS, TRADE_TIMEINFORCE, TRADE_TYPE, TRADE_SIDE, TRADE_CREATION_DATE, TRADE_UPDATE_DATE) VALUES ('expert2@test.com',				5, 'Binance', '10', '10', '16300',	'16250', 'XRPBTC', '24695', 1605858714195, '16277',	'16277',	'1', 'NEW', 'GTO', 'LIMIT',		    'BUY',	'2019-04-28 07:06:18', '2020-05-22 22:52:52')
INSERT INTO dbo.TRADE(USER_EMAIL, STATUS_ID, TRADE_PLATFORM, TRADE_AMOUNT_SYMBOL1, TRADE_AMOUNT_SYMBOL2, TRADE_PAIR_LIMIT, TRADE_AMOUNT_LIMIT, TRADE_SYMBOL, TRADE_CLIENTORDERLIST, TRADE_TRANSACTIME, TRADE_PRICE, TRADE_ORIGQTY, TRADE_CUMMULATIVEQUOTEQTY, TRADE_STATUS, TRADE_TIMEINFORCE, TRADE_TYPE, TRADE_SIDE, TRADE_CREATION_DATE, TRADE_UPDATE_DATE) VALUES ('expert2@test.com',				5, 'Binance', '10', '10', '16300',	'16250', 'ETHBNB', '24695', 1605855587123, '16277',	'16277',	'1', 'NEW', 'GTO', 'TAKE_PROFIT',   'SELL', '2020-02-16 04:07:30', '2019-05-24 00:21:40')
INSERT INTO dbo.TRADE(USER_EMAIL, STATUS_ID, TRADE_PLATFORM, TRADE_AMOUNT_SYMBOL1, TRADE_AMOUNT_SYMBOL2, TRADE_PAIR_LIMIT, TRADE_AMOUNT_LIMIT, TRADE_SYMBOL, TRADE_CLIENTORDERLIST, TRADE_TRANSACTIME, TRADE_PRICE, TRADE_ORIGQTY, TRADE_CUMMULATIVEQUOTEQTY, TRADE_STATUS, TRADE_TIMEINFORCE, TRADE_TYPE, TRADE_SIDE, TRADE_CREATION_DATE, TRADE_UPDATE_DATE) VALUES ('Yang@nowhere.com',	            6, 'Binance', '10', '10', '16300',	'16250', 'EOSBTC', '24695', 1605898487854, '16277',	'16277',	'1', 'NEW', 'FOK', 'STOP_LOSS',	    'SELL', '2020-05-12 14:47:25', '2019-06-06 10:25:15')
INSERT INTO dbo.TRADE(USER_EMAIL, STATUS_ID, TRADE_PLATFORM, TRADE_AMOUNT_SYMBOL1, TRADE_AMOUNT_SYMBOL2, TRADE_PAIR_LIMIT, TRADE_AMOUNT_LIMIT, TRADE_SYMBOL, TRADE_CLIENTORDERLIST, TRADE_TRANSACTIME, TRADE_PRICE, TRADE_ORIGQTY, TRADE_CUMMULATIVEQUOTEQTY, TRADE_STATUS, TRADE_TIMEINFORCE, TRADE_TYPE, TRADE_SIDE, TRADE_CREATION_DATE, TRADE_UPDATE_DATE) VALUES ('Yang@nowhere.com',         	    1, 'Binance', '10', '10', '16300',	'16250', 'ETHBTC', '24695', 1605826263521, '16277',	'16277',	'1', 'NEW', 'IOC', 'MARKET',		'BUY',	'2019-11-18 19:25:13', '2019-10-10 09:45:36')
INSERT INTO dbo.TRADE(USER_EMAIL, STATUS_ID, TRADE_PLATFORM, TRADE_AMOUNT_SYMBOL1, TRADE_AMOUNT_SYMBOL2, TRADE_PAIR_LIMIT, TRADE_AMOUNT_LIMIT, TRADE_SYMBOL, TRADE_CLIENTORDERLIST, TRADE_TRANSACTIME, TRADE_PRICE, TRADE_ORIGQTY, TRADE_CUMMULATIVEQUOTEQTY, TRADE_STATUS, TRADE_TIMEINFORCE, TRADE_TYPE, TRADE_SIDE, TRADE_CREATION_DATE, TRADE_UPDATE_DATE) VALUES ('AbigailBowman2@nowhere.com',	5, 'Binance', '10', '10', '16300',	'16250', 'XRPBTC', '24695', 1605841461617, '16277',	'16277',	'1', 'NEW', 'GTO', 'LIMIT',		    'BUY',	'2019-01-02 09:09:09', '2020-09-30 05:00:04')
INSERT INTO dbo.TRADE(USER_EMAIL, STATUS_ID, TRADE_PLATFORM, TRADE_AMOUNT_SYMBOL1, TRADE_AMOUNT_SYMBOL2, TRADE_PAIR_LIMIT, TRADE_AMOUNT_LIMIT, TRADE_SYMBOL, TRADE_CLIENTORDERLIST, TRADE_TRANSACTIME, TRADE_PRICE, TRADE_ORIGQTY, TRADE_CUMMULATIVEQUOTEQTY, TRADE_STATUS, TRADE_TIMEINFORCE, TRADE_TYPE, TRADE_SIDE, TRADE_CREATION_DATE, TRADE_UPDATE_DATE) VALUES ('AbigailBowman2@nowhere.com',	5, 'Binance', '10', '10', '16300',	'16250', 'ETHBNB', '24695', 1605894498484, '16277',	'16277',	'1', 'NEW', 'IOC', 'TAKE_PROFIT',   'SELL', '2020-12-05 12:08:40', '2019-08-14 00:59:52')


INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'test@test.com', 1)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'test@test.com', 2)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'test@test.com', 3)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'test@test.com', 4)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'test@test.com', 5)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'user@test.com', 5)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'member@test.com', 3)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'member@test.com', 5)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'expert@test.com', 3)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'expert@test.com', 4)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'expert@test.com', 5)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'expert2@test.com', 3)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'expert2@test.com', 4)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'expert2@test.com', 5)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'admin@test.com', 1)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'admin@test.com', 2)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'admin@test.com', 3)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'admin@test.com', 4)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'admin@test.com', 5)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'staff@test.com', 2)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'staff@test.com', 3)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'staff@test.com', 4)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'staff@test.com', 5)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'Higdon@nowhere.com', 3)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'Higdon@nowhere.com', 5)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'LuluAlcorn949@example.com', 5)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'Yang@nowhere.com', 3)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'Yang@nowhere.com', 4)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'Yang@nowhere.com', 5)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'AbigailBowman2@nowhere.com', 3)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'AbigailBowman2@nowhere.com', 4)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'AbigailBowman2@nowhere.com', 5)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'DelmaAcevedo@example.com', 3)
INSERT INTO dbo.USER_PROFIL(USER_EMAIL, PROFIL_ID) VALUES (N'Dewayne_Penny@example.com', 5)



INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (1,  N'expert@test.com', 10, 10, '2020-10-21 19:40:13', '2020-11-16 03:03:34')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (2, N'test@test.com', 10, 10, '2020-03-11 19:40:13', '2020-04-16 03:03:34')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (12, N'expert2@test.com', 10, 10, '2020-10-01 20:07:53', '2020-11-07 05:47:59')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (4, N'expert@test.com', 10, 10, '2020-05-19 08:05:01', '2020-05-31 14:09:51')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (9, N'Higdon@nowhere.com', 10, 10, '2019-05-17 20:22:06', '2019-08-21 20:29:02')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (4, N'expert2@test.com', 10, 10, '2019-08-03 17:57:58', '2019-12-19 08:14:41')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (4, N'Higdon@nowhere.com', 10, 10, '2020-03-12 19:33:30', '2020-08-15 04:26:59')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (11, N'Higdon@nowhere.com', 10, 10, '2019-07-28 03:33:25', '2019-09-22 18:24:53')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (3, N'Yang@nowhere.com', 10, 10, '2019-05-20 08:08:46', '2019-08-09 21:18:35')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (11, N'Yang@nowhere.com', 10, 10, '2019-10-24 11:31:23', '2020-09-21 14:38:57')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (4, N'Yang@nowhere.com', 10, 10, '2020-09-23 22:26:22', '2020-10-04 18:39:22')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (8, N'AbigailBowman2@nowhere.com', 10, 10, '2019-02-04 01:31:19', '2020-04-16 09:52:35')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (5, N'AbigailBowman2@nowhere.com', 10, 10, '2019-04-04 01:31:19', '2020-04-16 09:52:35')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (5, N'expert@test.com', 10, 10, '2020-06-11 08:05:01', '2020-07-31 14:09:51')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (8, N'Higdon@nowhere.com', 10, 10, '2020-05-17 08:27:06', '2020-08-21 20:29:02')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (3, N'expert@test.com', 10, 10, '2020-08-11 14:35:15', '2020-10-18 00:59:22')
INSERT INTO dbo.USER_SUBSCRIBE_STRAT(STRATEGY_ID, USER_EMAIL, PRIME_SOLIDR, PRIME_EXPERT, SUBSCRIBE_STRAT_START_DATE, SUBSCRIBE_STRAT_END_DATE) VALUES (9, N'Yang@nowhere.com', 10, 10, '2020-08-10 08:08:46', '2019-11-09 21:18:35')




INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (1, '2019-02-09 05:55:37', 'BTC', 53481.88)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (1, '2019-04-01 04:57:31', 'BTC', 77903.72)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (1, '2019-08-28 21:08:16', 'BTC', 49289.15)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (2, '2019-05-01 23:50:57', 'LTC', 77327.98)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (2, '2019-03-23 00:52:36', 'LTC', 99.06)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (2, '2019-03-19 10:03:33', 'LTC', 82414.18)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (3, '2019-02-06 01:21:56', 'BNB', 4.37)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (3, '2020-05-29 12:25:10', 'BNB', 89593.19)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (3, '2019-05-28 19:38:45', 'BNB', 50970.99)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (2, '2020-05-29 15:32:43', 'LTC', 114.87)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (4, '2020-01-28 22:35:52', 'ETH', 78.61)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (2, '2019-09-03 22:48:22', 'LTC', 82109.49)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (3, '2020-02-05 05:28:05', 'BNB', 656.01)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (3, '2020-09-23 19:15:42', 'BNB', 12721.25)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (4, '2020-06-15 21:05:21', 'ETH', 3.02)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (4, '2020-06-28 21:35:38', 'ETH', 96317.43)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (4, '2019-06-01 04:13:25', 'ETH', 34131.93)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (5, '2020-06-09 04:21:36', 'XMR', 4.22)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (5, '2019-10-03 16:25:31', 'XMR', 12820.25)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (5, '2020-06-02 05:41:33', 'XMR', 51673.91)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (4, '2019-04-13 13:41:09', 'ETH', 74334.58)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (1, '2020-06-18 03:54:25', 'BTC', 79250.16)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (2, '2019-10-27 09:42:51', 'LTC', 89023.45)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (3, '2020-06-12 20:37:48', 'BNB', 17354.97)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (1, '2019-02-05 00:34:09', 'BTC', 73862.43)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (2, '2020-03-28 05:34:27', 'LTC', 7.48)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (3, '2020-10-10 18:45:05', 'BNB', 98.55)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (5, '2020-01-26 21:55:37', 'XMR', 8.08)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (1, '2020-04-17 18:43:30', 'BTC', 84645.25)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (3, '2019-07-18 15:08:49', 'BNB', 3102.75)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (2, '2019-12-26 18:13:57', 'LTC', 4295.5)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (2, '2020-08-30 15:42:48', 'LTC', 934.54)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (4, '2019-02-27 10:24:28', 'ETH', 20)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (4, '2019-12-05 10:06:38', 'ETH', 92122.87)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (5, '2020-05-24 10:16:39', 'XMR', 88648.48)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (2, '2020-04-23 05:28:14', 'LTC', 1.68)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (1, '2020-02-18 21:37:39', 'BTC', 20409.46)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (1, '2019-05-21 06:59:59', 'BTC', 1.62)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (3, '2019-11-03 18:06:40', 'BNB', 60493.03)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (2, '2020-05-12 16:40:28', 'LTC', 42433.73)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (3, '2019-08-04 22:33:24', 'BNB', 13936.6)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (4, '2019-10-15 00:17:10', 'ETH', 11166.27)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (4, '2020-10-07 16:38:09', 'ETH', 56424.55)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (4, '2020-05-21 19:21:20', 'ETH', 1.64)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (3, '2019-03-09 06:38:23', 'BNB', 81879.36)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (2, '2020-07-06 08:40:02', 'LTC', 39314.06)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (3, '2020-01-22 04:58:19', 'BNB', 72879.01)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (2, '2019-02-04 18:20:08', 'LTC', 18073.49)
INSERT INTO dbo.WALLET_HISTORY(WALLET_ID, WALLET_HISTORY_DATE, WALLET_HISTORY_SYMBOL, WALLET_HISTORY_TOTAL) VALUES (1, '2019-01-19 12:58:28', 'BTC', 94524.42)
