UPDATE dbo.STRATEGY
SET STRATEGY_PROFITABILITY = '20.00'
WHERE STRATEGY_ID = 1
UPDATE dbo.STRATEGY
SET STRATEGY_PROFITABILITY = '-5.02'
WHERE STRATEGY_ID = 2
UPDATE dbo.STRATEGY
SET STRATEGY_PROFITABILITY = '10.12'
WHERE STRATEGY_ID = 3
UPDATE dbo.STRATEGY
SET STRATEGY_PROFITABILITY = '5.00'
WHERE STRATEGY_ID = 4
UPDATE dbo.STRATEGY
SET STRATEGY_PROFITABILITY = '12.45'
WHERE STRATEGY_ID = 5
UPDATE dbo.STRATEGY
SET STRATEGY_PROFITABILITY = '20.06'
WHERE STRATEGY_ID = 6
UPDATE dbo.STRATEGY
SET STRATEGY_PROFITABILITY = '3.45'
WHERE STRATEGY_ID = 7
UPDATE dbo.STRATEGY
SET STRATEGY_PROFITABILITY = '10.00'
WHERE STRATEGY_ID = 8
UPDATE dbo.STRATEGY
SET STRATEGY_PROFITABILITY = '35.57'
WHERE STRATEGY_ID = 9
UPDATE dbo.STRATEGY
SET STRATEGY_PROFITABILITY = '15.00'
WHERE STRATEGY_ID = 10
UPDATE dbo.STRATEGY
SET STRATEGY_PROFITABILITY = '13.75'
WHERE STRATEGY_ID = 11
UPDATE dbo.STRATEGY
SET STRATEGY_PROFITABILITY = '27.97'
WHERE STRATEGY_ID = 12
