ALTER TABLE dbo.USER_SUBSCRIBE_STRAT
    ADD AMOUNT_AFFECT1 character varying(50) DEFAULT NULL;

ALTER TABLE dbo.USER_SUBSCRIBE_STRAT
    ADD SYMBOL_AFFECT1 character varying(50) DEFAULT NULL;

ALTER TABLE dbo.USER_SUBSCRIBE_STRAT
    ADD AMOUNT_AFFECT2 character varying(50) DEFAULT NULL;

ALTER TABLE dbo.USER_SUBSCRIBE_STRAT
    ADD SYMBOL_AFFECT2 character varying(50) DEFAULT NULL;


