UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '1000'
WHERE STRATEGY_ID = 1
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '500'
WHERE STRATEGY_ID = 2
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '750'
WHERE STRATEGY_ID = 3
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '800'
WHERE STRATEGY_ID = 4
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '1300'
WHERE STRATEGY_ID = 5
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '600'
WHERE STRATEGY_ID = 6
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '1000'
WHERE STRATEGY_ID = 7
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '500'
WHERE STRATEGY_ID = 8
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '550'
WHERE STRATEGY_ID = 9
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '666'
WHERE STRATEGY_ID = 10
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '750'
WHERE STRATEGY_ID = 11
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '1000'
WHERE STRATEGY_ID = 12
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '500'
WHERE STRATEGY_ID = 13
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '550'
WHERE STRATEGY_ID = 14
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '666'
WHERE STRATEGY_ID = 15
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '750'
WHERE STRATEGY_ID = 16
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT1 = '1000'
WHERE STRATEGY_ID = 17

UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'XRP'
WHERE STRATEGY_ID = 1
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 2
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 3
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 4
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 5
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 6
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 7
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 8
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 9
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 10
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 11
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 12
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 13
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 14
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 15
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 16
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT1 = 'BTC'
WHERE STRATEGY_ID = 17

UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '1000'
WHERE STRATEGY_ID = 1
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '500'
WHERE STRATEGY_ID = 2
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '750'
WHERE STRATEGY_ID = 3
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '800'
WHERE STRATEGY_ID = 4
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '1300'
WHERE STRATEGY_ID = 5
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '600'
WHERE STRATEGY_ID = 6
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '1000'
WHERE STRATEGY_ID = 7
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '500'
WHERE STRATEGY_ID = 8
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '550'
WHERE STRATEGY_ID = 9
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '666'
WHERE STRATEGY_ID = 10
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '750'
WHERE STRATEGY_ID = 11
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '1000'
WHERE STRATEGY_ID = 12
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '500'
WHERE STRATEGY_ID = 13
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '550'
WHERE STRATEGY_ID = 14
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '666'
WHERE STRATEGY_ID = 15
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '750'
WHERE STRATEGY_ID = 16
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET AMOUNT_AFFECT2 = '1000'
WHERE STRATEGY_ID = 17

UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'USDT'
WHERE STRATEGY_ID = 1
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'LIBRA'
WHERE STRATEGY_ID = 2
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'BNB'
WHERE STRATEGY_ID = 3
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'BNB'
WHERE STRATEGY_ID = 4
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'ETH'
WHERE STRATEGY_ID = 5
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'ETH'
WHERE STRATEGY_ID = 6
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'ETH'
WHERE STRATEGY_ID = 7
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'ETH'
WHERE STRATEGY_ID = 8
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'ETH'
WHERE STRATEGY_ID = 9
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'ETH'
WHERE STRATEGY_ID = 10
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'ETH'
WHERE STRATEGY_ID = 11
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'ETH'
WHERE STRATEGY_ID = 12
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'XRP'
WHERE STRATEGY_ID = 13
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'XRP'
WHERE STRATEGY_ID = 14
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'EOS'
WHERE STRATEGY_ID = 15
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'EOS'
WHERE STRATEGY_ID = 16
UPDATE dbo.USER_SUBSCRIBE_STRAT
SET SYMBOL_AFFECT2 = 'XLM'
WHERE STRATEGY_ID = 17
